---
#-------------------------------
# Site Settings
title: ì œì£¼í•œë¼ëŒ€í•™êµ ì¸ê³µì§€ëŠ¥í•™ê³¼ (Department of Artificial Intelligence)
logo: "/assets/images/logo/logo-name.png"
logo_dark: "/assets/images/logo/logo-name-dark.png"
description: "ì œì£¼í•œë¼ëŒ€í•™êµ ì¸ê³µì§€ëŠ¥í•™ê³¼ (Department of Artificial Intelligence, Cheju Halla University)"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.

#-------------------------------
# Author Settings
author_name: ì œì£¼í•œë¼ëŒ€í•™êµ (Cheju Halla University)

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "í•™ê³¼ì†Œê°œ"
      url: "/about/"
    - title: "êµìˆ˜ì†Œê°œ"
      url: "/faculty/"
    - title: "êµê³¼ê³¼ì •"
      url: "/curriculum/"
    # - title: "ì…í•™"
    #   url: "/admissions/"
    - title: "ì§„ë¡œ"
      url: "/career/"
    - title: "í•™ìƒì—°êµ¬"
      url: "/projects/"
    - title: "ì •ë³´ê´‘ì¥"
      url: "/posts/"
    - title: "ì˜¤ì‹œëŠ”ê¸¸"
      url: "/location/"
      # submenu:
      # - url: "/contact/"
      #   title: "Contact"
    # - title: "ê²Œì‹œíŒ"
    #   url: "https://chu-ai.imweb.me/"

#-------------------------------
# Social Settings
social:
  - { icon: "fa-solid fa-building-columns", link: "https://www.chu.ac.kr" }
  - { icon: "fa-brands fa-youtube", link: "https://www.youtube.com/watch?v=8c9910JKf34" }
  # - { icon: "fa-brands fa-instagram", link: "https://instagram.com" }
  # - { icon: "fa-brands fa-github", link: "https://github.com" }
  - { icon: "fa-solid fa-comment-medical fa-bounce", link: "https://open.kakao.com/o/sgdkXqDg" }
  # - { icon: "icon-kakao-talk", link: "https://accounts.kakao.com" } # dark mode is not working

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: <span>ì¸ê³µì§€ëŠ¥í•™ê³¼</span> # Department of <span><i>Artificial Intelligence Engineering</i></span>, Cheju Halla University
  hero_description: 4ì°¨ì‚°ì—…í˜ëª…ìœ¼ë¡œ ì§„í™”í•˜ëŠ” ë¯¸ë˜ì‚°ì—…ì‚¬íšŒì—ì„œ ìš”êµ¬í•˜ëŠ” ì¸ê³µì§€ëŠ¥, ë¹…ë°ì´í„°, ì‚¬ì´ë²„ë³´ì•ˆ, ì‚¬ë¬¼ì¸í„°ë„· ë° ì§€ëŠ¥í˜• ë¡œë´‡ ê´€ë ¨ ì°¨ì„¸ëŒ€ í•µì‹¬ ì „ë¬¸ê¸°ìˆ ì¸ë ¥ ì–‘ì„±í•™ê³¼!!


  hero_image: "/assets/images/home/bg.png"
  hero_button_contact: 
  hero_button_about: í•™ê³¼ì†Œê°œ

#-------------------------------
# Projects Settings
section_projects_title: ğŸ‘¨ğŸ»â€ğŸ’» Selected Projects

#-------------------------------
# Testimonials Section
section_testimonial_title: ğŸ™‚ What Students Say

testimonial_items:
  - name: "ì´ê·œë²”"
    image: "/assets/images/testimonial/student-1.png"
    designation: "2024ë…„ í•™ìƒíšŒì¥"
    link: "https://twitter.com/"
    content: "ì¸ê³µì§€ëŠ¥ê³µí•™ê³¼ëŠ” í˜„ëŒ€ ê¸°ìˆ ì˜ ì¤‘ì‹¬ì— ìˆëŠ” ë¶„ì•¼ë¡œ, ê¸°ì´ˆì ì¸ ì»´í“¨í„° ê³¼í•™, ìˆ˜í•™, í†µê³„í•™, ë¨¸ì‹ ëŸ¬ë‹, ë”¥ëŸ¬ë‹ ë“±ì˜ ì´ë¡ ì„ í† ëŒ€ë¡œ í˜ì‹ ì ì¸ ì¸ê³µì§€ëŠ¥ ì‹œìŠ¤í…œì„ ì„¤ê³„, ê°œë°œ, ìµœì í™”í•˜ëŠ” í•™ë¬¸ì„ íƒêµ¬í•©ë‹ˆë‹¤. ì´ ê³¼ì •ì—ì„œ í•™ìƒë“¤ì€ ë°ì´í„° ë¶„ì„, íŒ¨í„´ ì¸ì‹, ìì—°ì–´ ì²˜ë¦¬, ì»´í“¨í„° ë¹„ì „ ë“± ë‹¤ì–‘í•œ ë¶„ì•¼ì—ì„œì˜ ë¬¸ì œ í•´ê²°ì„ ìœ„í•œ ì•Œê³ ë¦¬ì¦˜ì„ í•™ìŠµí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."

  - name: "ì–‘í•„ì„±"
    image: "/assets/images/testimonial/student-2.png"
    designation: "21í•™ë²ˆ"
    link: "https://facebook.com/"
    content: "ì œì£¼í•œë¼ëŒ€í•™êµ ì¸ê³µì§€ëŠ¥ê³µí•™ê³¼ëŠ” ìµœì‹  ê¸°ìˆ ì„ ë°˜ì˜í•œ êµìœ¡ê³¼ì •ì„ í†µí•´ í•™ìƒë“¤ì´ AI ë¶„ì•¼ì—ì„œ ì•ì„œ ë‚˜ê°ˆ ìˆ˜ ìˆë„ë¡ ë•ìŠµë‹ˆë‹¤. Chat GPTì™€ ê°™ì€ ëŒ€ê·œëª¨ ì–¸ì–´ ëª¨ë¸(LLM)ì„ ë‹¤ë£¨ëŠ” ì‹¤ìŠµì„ í†µí•´ ìì—°ì–´ ì²˜ë¦¬ ëŠ¥ë ¥ì„ í‚¤ìš¸ ìˆ˜ ìˆìœ¼ë©°, ì»´í“¨í„° ë¹„ì „ ë¶„ì•¼ì—ì„œì˜ ë‹¤ì–‘í•œ í”„ë¡œì íŠ¸ë¥¼ í†µí•´ ì‹œê° ì¸ê³µì§€ëŠ¥ ê¸°ìˆ ì„ ì‹¬ë„ ìˆê²Œ ë°°ìš¸ ìˆ˜ ìˆìŠµë‹ˆë‹¤. ë”¥ëŸ¬ë‹ê³¼ ë°ì´í„° ì²˜ë¦¬ ëŠ¥ë ¥ë„ ì²´ê³„ì ìœ¼ë¡œ í–¥ìƒì‹œí‚¬ ìˆ˜ ìˆì–´, ì‹¤ë¬´ì— ë°”ë¡œ ì ìš© ê°€ëŠ¥í•œ ìŠ¤í‚¬ì„ ìŠµë“í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ì¸ê³µì§€ëŠ¥ì— ëŒ€í•œ ì—´ì •ì´ ìˆë‹¤ë©´, ì œì£¼í•œë¼ëŒ€í•™êµ ì¸ê³µì§€ëŠ¥ê³µí•™ê³¼ëŠ” í›„íšŒ ì—†ëŠ” ì„ íƒì´ ë  ê²ƒì…ë‹ˆë‹¤."

  - name: "ê¹€ì€ì§€"
    image: "/assets/images/testimonial/student-3.png"
    designation: "2022ë…„ í•™ìƒíšŒì¥"
    link: "https://twitter.com/"
    content: "ì œì£¼í•œë¼ëŒ€í•™êµ ì¸ê³µì§€ëŠ¥ê³µí•™ê³¼ëŠ” ì»´í“¨í„° ë¹„ì „, llm, Text-to-Image ë“± ë‹¤ì–‘í•œ ì£¼ì œì— ëŒ€í•œ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ìµœì‹  ê¸°ìˆ ê³¼ ì—°êµ¬ë¥¼ ë‹¤ë£¨ë©°, í•™ìƒë“¤ì´ ì´ë¡ ê³¼ ì‹¤ìŠµì„ ê· í˜• ìˆê²Œ ë°°ìš¸ ìˆ˜ ìˆëŠ” í™˜ê²½ì„ ì œê³µí•©ë‹ˆë‹¤. ë˜í•œ, ì „ë¬¸ êµìˆ˜ì§„ê³¼ì˜ ê¸´ë°€í•œ í˜‘ì—…ì„ í†µí•´ ê¹Šì´ ìˆëŠ” ì§€ì‹ì„ ìŒ“ê³ , ì‹¤ì œ ë¬¸ì œ í•´ê²° ëŠ¥ë ¥ì„ í‚¤ìš¸ ìˆ˜ ìˆìŠµë‹ˆë‹¤. ì´ëŸ¬í•œ ì ì—ì„œ ì¸ê³µì§€ëŠ¥ê³µí•™ê³¼ëŠ” ì¸ê³µì§€ëŠ¥ ë¶„ì•¼ì— ê´€ì‹¬ì´ ìˆëŠ” í•™ìƒë“¤ì—ê²Œ ìµœê³ ì˜ ì„ íƒì´ ë  ê²ƒì…ë‹ˆë‹¤."

#-------------------------------
# Blog Section
section_blog_title: ğŸ“š Read Latest Posts
#-------------------------------

# Tags Section
section_tags_title: âœŒï¸ Explore Topics

#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: ì¸ê³µì§€ëŠ¥í•™ê³¼ ë‰´ìŠ¤ë ˆí„° êµ¬ë…
  mailchimp_identifier: halla.us21.list-manage.com/subscribe/post?u=2bb7450a6c4f2df4098555a00&amp;id=87dede211f&amp
  mailchimp_input_text: ì´ë©”ì¼ ì£¼ì†Œë¥¼ ì…ë ¥í•´ ì£¼ì„¸ìš”.
  mailchimp_background_image: /assets/images/mailchimp/subscribe-bg.png

#-------------------------------
# Footer Settings
footer_description: (63092) ì œì£¼íŠ¹ë³„ìì¹˜ë„ ì œì£¼ì‹œ í•œë¼ëŒ€í•™ë¡œ 38 <br>Tel. 064-741-7575 / Fax. 064-747-3989 <br>38 Halladaehak-ro, Jeju-si, Jeju Special Self-Governing Province, 63092 Republic of Korea <br>Tel. +82-64-741-7575 / Fax. +82-64-747-3989

#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "í•™ê³¼ì†Œê°œ"
      url: "/about/"
    - title: "êµìˆ˜ì†Œê°œ"
      url: "/faculty/"
    - title: "êµê³¼ê³¼ì •"
      url: "/curriculum/"
    # - title: "ì…í•™"
    #   url: "/admissions/"
    - title: "ì§„ë¡œ"
      url: "/career/"
    - title: "ë¦¬ì„œì¹˜"
      url: "/projects/"
    - title: "ì •ë³´ê´‘ì¥"
      url: "/posts/"
    - title: "ì˜¤ì‹œëŠ”ê¸¸"
      url: "/location/"
    # - title: "ê²Œì‹œíŒ"
    #   url: "https://chu-ai.imweb.me/"

#-------------------------------
# Contact Settings
contact:
  email: yj.lee@chu.ac.kr # Add your form_id
  description: If you have any questions, please feel free to contact us.

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
# Add your shortname for Disqus Comment.
disqus_identifier: # halla-ai 

#-------------------------------
# Google Analytics
google_analytics: G-QP4FVB9F1X

#-------------------------------
# Giscus comments (RECOMMENDED)
# Follow instructions on https://giscus.app/ to setup for your repo to fill out
# the information below.
giscus:
  enable: true
  repo: chu-aie/.github # <your-github-user-name>/<your-github-repo-name>
  repo_id: R_kgDOKLOxpQ
  category: Comments # name of the category under which discussions will be created
  category_id: DIC_kwDOKLOxpc4CZjrm
  mapping: pathname
  strict: 0
  reactions_enabled: 1 # enable (1) or disable (0) emoji reactions
  input_position: top # whether to display input form below (bottom) or above (top) the comments
  theme: light # name of the color scheme
  emit_metadata: 0
  lang: ko
  loading: lazy # lazy, lazy-once, or immediate
